apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: myapp
    image: busybox
    command: ["sh", "-c", "echo USER=$USERNAME && echo PASS=$PASSWORD && sleep 3600"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
