apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - port: 80              # Exposed outside
      targetPort: 3000      # Where the app listens *inside* container
      nodePort: 30080       # Exposed on Node IP
  type: NodePort
